config/routes.rb
Rails.application.routes.draw do
 
  devise_for :reviewers#, controllers: { omniauth_callbacks: 'reviewer/omniauth_callbacks' }
  devise_for :restaurants

  devise_for :omni_users, controllers: { omniauth_callbacks: 'omni_users/omniauth_callbacks' }

  get 'search/index'
  get 'search/show'
  get 'search/edit'
  get 'search/update'
  get 'search/search_restaurant'
  get 'search/search_dish'
  get 'search/index'
  get 'search/show'
  get 'search/edit'
  get 'search/update'
  get 'home/index'
# This is for being able of testing the application with cucumber. Since we are not using devise defaults login
  match 'login/:id' => 'restaurant#login', :as => 'login', :via => [:get] if Rails.env.test?

  
  resources :reports, :except => :index
  resources :dishes, :except => :index
  resources :restaurants, :except => :index
  resources :reviews, :except => :index
  resources :reviewers, :except => :index
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "home#index"

  get '/search_restaurant', to: 'search#search_restaurant'
  get '/search_dish', to: 'search#search_dish'

  #default, per percorsi inesistenti (es.No route matches [GET])
  #se danno problemi commentare
  #get '*all', to: 'home#index', constraints: lambda { |req|
   # req.path.exclude? 'rails/active_storage'
  #}
  
  #le recensioni possono essere viste ed accedute solo attraverso i ristoranti e recensori, ma non tutte le funzionalita'
  #resources :restaurant do
	#	resources :reviews, only: [:new, :show, :create]
  #  resources :dish, only: [:new, :show, :create, :delete]
	#end
  #idem
  #resources :reviewer do
	#	resources :reviews, only: [:show, :edit, :index]
	#end

  #resources :restaurant, only: [:index, :new, :show, :create]


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homepage</title>
    <%= stylesheet_link_tag "homepage.css" %>
</head>
<body>
    <div id = "middle">
        <div id = "col1">
        <div id = "carousel_homepage">
            <% i = 0 + rand(7) %>
            <% img_path = "hp_" + i.to_s + ".jpg"%>
            <%=image_tag(img_path, :class => "img_carosello", :alt => "image of homepage")%>
        </div>
        <%#=Reviewer.find(11).destroy%>
        <%#=Restaurant.find(1).destroy%>
        <%#=session[:calling_path]%>
        
        <%#= TasteAdvisorMailer.with(user: current_reviewer, type: "Reviewer").welcome_email.deliver!%>
        
        <!-- 
        <%#= HO LAVORATO SU DEI FILE e dei permessi (per mostrare le img) , questi si chiamano asset e vanno inseriti in app/asset/image %>
            <div id = "carousel_homepage" class = "carousel slide" data-bs-ride="carousel">
                <div class = "carousel-inner">
                    
                    <div class = "carousel-item active">
                        <%#=image_tag("pizza-sample1.jpg", :class => "d-block w-auto", :alt => "image of pizza")%>
                    </div>
                    <div class = "carousel-item">
                        <%#=image_tag("pizza-sample2.jpg", :class => "d-block w-auto", :alt => "image of pizza")%>
                    </div>
                    
                </div>
            </div>
            -->
        </div>
        <div id = "col2">
            <%= render  "search/form" %>
            <div id = "description">Benvenuto su TasteAdvisor! Divertiti a scoprire nuovi piatti e nuovi ristoranti nel mondo. Cerca piatti per categoria, per nome oppure solo quelli del tuo ristorante preferito per rimanere sempre aggiornato! Potrai usufruire delle esperienze degli altri utenti per conoscere dettagli sui piatti offerti dai vari ristoranti nella tua zona o, se ti registri come recensore, essere tu di aiuto ad altre persone con le tue recensioni. Se sei un proprietario di un ristorante, infine, non aspettare a creare un profilo ristoratore per mostrare agli altri i tuoi fantastici piatti. </div>
        </div>
    </div>
</body>


</html>

app/views/home/index2.html.erb
<h1>Home#index</h1>
<% if reviewer_signed_in? %>

    UTENTE RECENSORE<br>

    ID:<%= current_reviewer.id %><br />
    USERNAME:<%= current_reviewer.username %><br />
    NAME:<%= current_reviewer.name %><br />
    SURNAME:<%= current_reviewer.surname %><br />
    TEL:<%= current_reviewer.telephone_number%><br />
    EMAIL:<%= current_reviewer.email %><br />


    <%= button_to "logout", destroy_reviewer_session_path, method: :delete  %>
<% elsif restaurant_signed_in? %>

    UTENTE RISTORANTE<br>

    ID:<%= current_restaurant.id %><br />
    USERNAME:<%= current_restaurant.username %><br />
    NAME:<%= current_restaurant.name %><br />
    TEL:<%= current_restaurant.telephone_number%><br />
    ADDRESS:<%= current_restaurant.address%><br />
    EMAIL:<%= current_restaurant.email %><br />

    <%= link_to "vai ai piatti", dishes_path, method: :get%>
    <%= button_to "logout", destroy_restaurant_session_path, method: :delete  %>
<%else%>
    <%= button_to "Sign in reviewer", new_reviewer_session_path %>
    <%= button_to "Sign in restaurant", new_restaurant_session_path %>

    <br>

    <%= button_to "Sign up reviewer", new_reviewer_registration_path , method: :get, :class => "btn btn-success" %>
    <%= button_to "Sign up restaurant", new_restaurant_registration_path , method: :get%> 
    <p>Find me in app/views/home/index.html.erb</p>
<%end%>