config/routes.rb
Rails.application.routes.draw do
 
  devise_for :reviewers#, controllers: { omniauth_callbacks: 'reviewer/omniauth_callbacks' }
  devise_for :restaurants

  devise_for :omni_users, controllers: { omniauth_callbacks: 'omni_users/omniauth_callbacks' }

  get 'search/index'
  get 'search/show'
  get 'search/edit'
  get 'search/update'
  get 'search/search_restaurant'
  get 'search/search_dish'
  get 'search/index'
  get 'search/show'
  get 'search/edit'
  get 'search/update'
  get 'home/index'
# This is for being able of testing the application with cucumber. Since we are not using devise defaults login
  match 'login/:id' => 'restaurant#login', :as => 'login', :via => [:get] if Rails.env.test?

  
  resources :reports, :except => :index
  resources :dishes, :except => :index
  resources :restaurants, :except => :index
  resources :reviews, :except => :index
  resources :reviewers, :except => :index
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "home#index"

  get '/search_restaurant', to: 'search#search_restaurant'
  get '/search_dish', to: 'search#search_dish'

  #default, per percorsi inesistenti (es.No route matches [GET])
  #se danno problemi commentare
  #get '*all', to: 'home#index', constraints: lambda { |req|
   # req.path.exclude? 'rails/active_storage'
  #}
  
  #le recensioni possono essere viste ed accedute solo attraverso i ristoranti e recensori, ma non tutte le funzionalita'
  #resources :restaurant do
	#	resources :reviews, only: [:new, :show, :create]
  #  resources :dish, only: [:new, :show, :create, :delete]
	#end
  #idem
  #resources :reviewer do
	#	resources :reviews, only: [:show, :edit, :index]
	#end

  #resources :restaurant, only: [:index, :new, :show, :create]


end

app/models/dish.rb
class Dish < ApplicationRecord
    validates :name, :price, :category, presence: true    
    validates :category, inclusion: { in: 0..3 }
    
    belongs_to :restaurant
    has_many :review

    has_many_attached :images, service: :google
    validates :images,  blob: { content_type: :image }

    before_destroy :destroy_referenced_reviews

    private
        def destroy_referenced_reviews
            (Review.all).each do |review|
                if(review.dish_id == self.id)
                    review.destroy
                end
            end
        end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: %i[ show edit update destroy ]

  # GET /dishes or /dishes.json
  def index
    @dishes = Dish.all
  end

  # GET /dishes/1 or /dishes/1.json
  def show
    
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes or /dishes.json
  def create
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to dish_url(@dish), notice: "Il piatto è stato creato correttamente" }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1 or /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to dish_url(@dish), notice: "Il piatto è stato aggiornato correttamente" }
        format.json { render :show, status: :ok, location: @dish }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1 or /dishes/1.json
  def destroy
    @dish.destroy

    respond_to do |format|
      format.html { redirect_to dishes_url, notice: "Il piatto è stato cancellato correttamente" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dish_params
      params.require(:dish).permit(:name, :number_of_reviews, :price, :category, :avg_rating, :imgs, :restaurant_id, :description, :ingredients, images: [])
      #credits. https://stackoverflow.com/questions/43217456/cant-update-user-belongs-to-association-in-rails
      #altrimenti non passo il valore di restaurant_id (prima non era presente)
    end
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_dish.html.erb
<div id="<%= dom_id dish %>">

  ID: <%= dish.id %><br>
  NAME: <%= dish.name %><br>
  CATEGORY: <%= dish.category %><br>
  AVG_RATING: <%= dish.avg_rating%><br>
  <%if dish.restaurant_id != nil %>
    RESTAURANT: <%= Restaurant.find(dish.restaurant_id).name %><br>
  <%end%>
  RESTAURANT ID: <%= dish.restaurant_id %><br>
  PRICE: <%= dish.price %><br>
  DESCRIPTION: <%= dish.description %><br>
  INGREDIENTS: <%= dish.ingredients %><br>
  <%if dish.images[0] != nil%>

    FOTO:  
    <% i = 0 %>
    <% while dish.images[i] != nil%>
        <img src="<%= url_for(dish.images[i])%>" alt="foto_piatto" width="300" height="300">
        <%i += 1%>
    <%end%>
    <br>
    <%session[:save_dish] = dish.id%>

  <%end%>
</div>

app/views/dishes/_form.html.erb
<%= stylesheet_link_tag "general_tags.css" %>
<%= stylesheet_link_tag "modPiatto.css" %>

<%= form_with(model: dish) do |form| %>
  <% if dish.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
        <% dish.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div id = "middle">

  <div id = "row_m1">

    <div id = "col_m1">
      <div class = "field_div">
        <%= form.file_field :images, multiple: true, direct_upload: false, accept:"image/*" %>
      </div>
      <div class = "field_div">
        <%= form.label :Nome, style: "display: block" %>
        <%= form.text_field :name %>
      </div>
      <div class = "field_div">
        <%= form.label :Descrizione, style: "display: block" %>
        <%= form.text_field :description %>
      </div>
    </div>

    <div id = "col_m2">
      <div class = "field_div">
        <%= form.label :Categoria, style: "display: block" %>
          <%= form.select :category, [ ["Antipasti", "0"], ["Primi", "1"], ["Secondi", "2"], ["Dolci", "3"] ], autofocus: true, autocomplete: "category" %>
      </div>
      <div class = "field_div">
        <%= form.label :Prezzo, style: "display: block" %>
        <%= form.text_field :price %>
      </div>
      
      <div class = "field_div">
        <%= form.label :Ingredienti, style: "display: block" %>
        <%= form.text_field :ingredients %>
      </div>

      <!--
      <div>
        <% form.label :number_of_reviews, style: "display: block" %>
        <%= form.number_field :number_of_reviews, value: 0, type: :hidden %>
      </div>

      <div>
        <% form.label :avg_rating, style: "display: block" %>
        <%= form.text_field :avg_rating, value: 0, type: :hidden %>
      </div>
      -->

    </div>
  </div>

  <div id = "row_m2">
    <div>
        <%= form.submit "Conferma", :class => "btn btn-success btn-opt" %>
        <%= link_to "Annulla", current_restaurant, :class => "btn btn-danger btn-opt"%>
      </div>
    <% end %>
  </div>

</div>

app/views/dishes/_form1.html.erb
<%= form_with(model: dish) do |form| %>
  <% if dish.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
        <% dish.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <% form.label :number_of_reviews, style: "display: block" %>
    <%= form.number_field :number_of_reviews, value: 0, type: :hidden %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.number_field :category ,in: 0..3 %>

  </div>

  <div>
    <% form.label :avg_rating, style: "display: block" %>
    <%= form.text_field :avg_rating, value: 0, type: :hidden %>
  </div>

  <div>
    <%= form.label :imgs, style: "display: block" %>
    <%= form.text_field :imgs %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
  <%if @dish.restaurant_id == current_restaurant.id %> 
    <%= render "form", dish: @dish %>
  <% else%>
    NON PERMESSO!
  <%end%>

<!-- 
<div>
  <%= link_to "Show this dish", @dish %> |
  <%= link_to "Back to dishes", dishes_path %>
</div>
-->

app/views/dishes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Dishes</h1>
<%if restaurant_signed_in?%>

  <div id="dishes">
    <% @dishes.each do |dish| %>
      <%if dish.restaurant_id == current_restaurant.id %>
        <%= render dish %>
        <p> <%= link_to "Show this dish", dish %> </p> 
      <%end%>
    <% end %>
  </div>

  <%= link_to "New dish", new_dish_path %>

<%#elsif reviewer_signed_in?%>
<%elsif reviewer_signed_in?%>
  <div id="dishes">
    <% @dishes.each do |dish| %>
      <%= render dish %>
      <p> <%= link_to "Show this dish", dish %> </p>
    <% end %>
  </div>
<%else%>
  DEVI LOGGARE 
  <br>
  <%= link_to "Log in", new_session_path("restaurant") %><br />

<%end%>

app/views/dishes/new.html.erb
<%= stylesheet_link_tag "modPiatto.css"%>
<div id = "middle">
  <%if restaurant_signed_in?%>
    <%= form_for(@dish) do |f| %>
      <div id = "row_m1">
      
      <div id = "col_m1">
        <div class = "field_div">
          <%= f.file_field :images, multiple: true, direct_upload: false %>  
          <!-- implementare nel lato backend -->
        </div>
        <div class = "field_div">
          <% f.label :name %>Nome
          <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
        </div>
        <div class = "field_div">
          Descrizione
          <%= f.text_field :description, autofocus: true, autocomplete: "description" %>
          <!-- implementare nel lato backend -->
        </div>  
      
      </div>

      <div id = "col_m2">
        <div class = "field_div">
          <% f.label :category %>Categoria<br>
          <%= f.select :category, [ ["Antipasti", "0"], ["Primi", "1"], ["Secondi", "2"], ["Dolci", "3"] ], autofocus: true, autocomplete: "category" %>
        </div>
        <div class = "field_div">
          <% f.label :price %>Prezzo<br>
          <%= f.text_field :price, autofocus: true, autocomplete: "price" %>
        </div>  
        <div class = "field_div">Ingredienti:<br>
          <%= f.text_field :ingredients, autofocus: true, autocomplete: "ingredients" %>
        </div>  
      </div>
    
    </div>

      <!-- <%= current_restaurant.id%> -->
      <div class="field">
        <%= f.hidden_field :avg_rating, value: 0 %>
        <%= f.hidden_field :number_of_reviews, value: 0 %>
        <%= f.hidden_field :restaurant_id, value: current_restaurant.id%>
      </div>
    <div id = "row_m2">
      <div>
          <%= link_to "Annulla", current_restaurant, :class => "btn btn-danger" %>
          <%= f.submit "Conferma", :class => "btn btn-success"%>
      </div>
    </div>
    
    <% end %>

    <br>

  <%elsif reviewer_signed_in? %>
    DEVI LOGGARE COME RISTORANTE PER POTER AGGIUNGERE PIATTI!
  <%else%>
    DEVI LOGGARE!
  <%end%>
</div>

app/views/dishes/show.html.erb
<%= stylesheet_link_tag "piatto.css" %>

 <div id = "middle">
        <div id = "col1">
            <div id = "plate_name"><%= @dish.name %></div>
            <div id = "foto_piatto" class="carousel carousel-fade" data-bs-ride="carousel">
                <div class="carousel-inner">
                    <% i = 0 %>
                    <% while @dish.images[i] != nil%>
                        <% if (i == 0) %>
                            <div class="carousel-item active">
                        <% else %>
                            <div class="carousel-item">
                        <% end %>
                        <img src="<%= url_for(@dish.images[i])%>" alt="foto_piatto" id="dish_pic">
                        <%i += 1%>
                        </div>
                    <%end%>
                    <%if i == 0%>
                        <%= image_tag("missing_dish.png", :class => "dish_pic")%>
                    <%end%>
                </div>
            </div>
            <div id = "actions">

            <div id="fb-root"></div>
            <script async defer crossorigin="anonymous" src="https://connect.facebook.net/it_IT/sdk.js#xfbml=1&version=v15.0&appId=891463521856520&autoLogAppEvents=1" nonce="9dbJ8tPj"></script>

            <!-- Your share button code -->
            <div class="fb-share-button" 
            data-href="https://tasteadvisor.herokuapp.com/dishes/<%= @dish.id%>" 
            data-layout="button_count" id = "fbook-btn" data-size="large">
            </div>
                <%if reviewer_signed_in?%>
                    <%#POSSO RECENSIRE UNA SOLA VOLTA UN PIATTO%>
                    <%check_exist = 0.0%>
                    <% (Review.all).each do |review| %>
                        <%if review.dish_id == @dish.id and review.reviewer_id == current_reviewer.id %>
                            <%check_exist = 1.0%>
                        <%end%>
                    <%end%>
                    <%if check_exist == 0.0%>
                        <div class = "div_review"><%= link_to "Lascia recensione", new_review_path(dish_id: @dish.id), :class => "btn btn-warning", :id =>"review_btn" %></div>       
                    <%end%>

                <%elsif restaurant_signed_in?%>
                    <!-- Alert passato come parametro alla richiesta url di ricaricamento della pagina-->
                    <div id = "review"><%= link_to "Lascia recensione", dish_path(@dish.id, flash_alert: "Non puoi recensire un piatto perchè non sei un recensore"), :class => "btn btn-warning btn-custom"%><br></div>
                    <% flash.now[:alert] = params[:flash_alert] if params[:flash_alert] %>
                <%else%>
                    <div id = "review"><%= link_to "Lascia recensione", new_reviewer_session_path(flash_alert: "Devi prima accedere come recensore"), :class => "btn btn-warning btn-custom" %><br></div>
                <%end%>
                <div id = "report">
                    <%if reviewer_signed_in? %>

                        <%check_exist = 0.0%>
                        <%#POSSO SEGNALARE UNA SOLA VOLTA UN PIATTO%>
                        <% (Report.all).each do |report| %>
                            <%#= render report%>
                            <%if report.reporterId == current_reviewer.id  and report.targetType == "dish" and report.targetId == @dish.id %>
                                <%check_exist = 1.0%>
                            <%end%>
                        <%end%>

                        <%if check_exist == 0.0%>
                            <%= form_with url: new_report_path, method: :get do |form| %>
                                <%= form.hidden_field :report_id, value: @dish.id%>
                                <%= form.hidden_field :report_type, value:"dish"%>
                                <%= form.hidden_field :reporter_id, value: current_reviewer.id %>
                                <%= submit_tag "Segnala", :class => "btn btn-danger btn-custom" %>
                            <% end %>
                        <%end%>
                        
                    <%elsif (restaurant_signed_in?) and (current_restaurant == @dish.restaurant)%>
                        <%= link_to "Segnala", dish_path(@dish.id, flash_alert: "Non puoi segnalare un tuo piatto"), :class => "btn btn-danger btn-custom" %>
                        <% flash.now[:alert] = params[:flash_alert] if params[:flash_alert] %>
                    <%elsif (restaurant_signed_in?) and (current_restaurant != @dish.restaurant)%>
                        <%= link_to "Segnala", dish_path(@dish.id, flash_alert: "Non puoi segnalare un piatto perchè non sei un recensore"), :class => "btn btn-danger btn-custom" %>
                        <% flash.now[:alert] = params[:flash_alert] if params[:flash_alert] %>
                    <%else%>
                        <%= link_to "Segnala", new_reviewer_session_path(flash_alert: "Devi prima accedere"), :class => "btn btn-danger btn-custom" %>
                    <%end%>
                </div>
            </div>
        </div>
        <div id = "col2">
            <div id = "plate_desc">
                <div id = "det_col1">
                    <div id = "description_plate">
                    <% if @dish.description == nil || @dish.description.length == 0 %> 
                        Nessuna descrizione disponibile per questo piatto
                    <% else %>
                        Descrizione: <%= @dish.description %>
                    <% end %>
                    </div>
                    <div id = "plate_ingredients">
                        <% if @dish.ingredients == nil || @dish.ingredients.length == 0 %> 
                            Nessun ingrediente disponibile per questo piatto
                        <% else %>
                            Ingredienti: <%= @dish.ingredients %>
                        <% end %>
                    </div>
                    <div id = "category">
                        <label id = "category_label">Categoria: </label>
                        <%if @dish.category == 0%>
                            <div id = "result"> <%= "Antipasti" %></div>
                        <%elsif @dish.category == 1 %>
                            <div id = "result"> <%= "Primi" %></div>
                        <%elsif @dish.category == 2 %>
                            <div id = "result"> <%= "Secondi" %></div>
                        <%elsif @dish.category == 3 %>
                            <div id = "result"> <%= "Dolci" %></div>
                        <%end%>
                    </div>
                    <div class = "rating">
                        <div class = "rating_score">
                            <label id = "rating_label">Rating: </label>
                            <div class = "value" id = "rating_value"> <i><%= @dish.avg_rating.truncate(2) %> /5</i> </div>
                        </div>
                        <div class = "pb" id = "rating_pb">
                            <div class = "progress">
                                <div class = "progress-bar progress-bar-striped bg-info" role = "progressbar" style="width: <%= @dish.avg_rating*20%>%" aria-valuenow="<%= @dish.avg_rating*20 %>" aria-valuemin="0" aria-valuemax="20"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div id = "det_col2">
                    <%if (@dish.restaurant_id != nil)%>
                    <% username = Restaurant.find(@dish.restaurant_id).username %>
                    <div id = "restaurant">Ristorante : <%= link_to username, restaurant_path(@dish.restaurant_id) %></div>
                    <%end%>
                    <div id = "price"> Prezzo : <%= @dish.price %> €</div>
                </div>
            </div>
            <div id = "reviews">
                <div id = "review_label"> Recensioni: <%= @dish.number_of_reviews %></div>
                <div id = "reviews_list">
                    <% (Review.all).each do |review| %>
                        <%if @dish.id == review.dish_id %>
                        <%= link_to review_path(review) do %>
                            <div class ="review">
                            <div class="img_review">
                                <%if Reviewer.find(review.reviewer_id).profile_picture.attached?%>
                                    <img class = "reviewer_img" src="<%= url_for(Reviewer.find(review.reviewer_id).profile_picture)%>" alt="Immagine del recensore">
                                <% else %>
                                      <%= image_tag("missing_user.png", :class => "reviewer_img")%>
                                <%end%>
                            </div>
                            <div class="review_info">
                                <div class="username_and_rating">
                                    <div >
                                        <%=Reviewer.find(review.reviewer_id).username%>
                                    </div>
                                    <div class = "rating">
                                        <div class = "rating_score">
                                            <label id = "rating_label">Rating: </label>
                                            <div class = "value" id = "rating_value">
                                                <i> <%= @avg_rate = ((review.rating1 + review.rating2 + review.rating3).fdiv(3)).truncate(2) %> /5 </i>
                                            </div>
                                        </div>
                                        <div class = "pb" id = "rating_pb">
                                            <div class = "progress">
                                                <div class = "progress-bar progress-bar-striped bg-info" role = "progressbar" style="width: <%= @avg_rate.round(2) * 20%>%" aria-valuenow="<%= @avg_rate.round(2) * 20%>" aria-valuemin="0" aria-valuemax="100"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class = "rev_text">
                                    <%= review.description %>
                                </div>
                            </div>
                        </div>
                        
                        <%end%>
                        <%end%>
                <% end %>
                </div>
            </div>
        </div>
    </div>

            <script>(function(d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id)) return;
                js = d.createElement(s); js.id = id;
                js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0";
                fjs.parentNode.insertBefore(js, fjs);
                }(document, 'script', 'facebook-jssdk'));
            </script>

app/views/dishes/show1.html.erb
<p style="color: green"><%= notice %></p>

<%= render @dish %>

<%= link_to "Back to dishes", dishes_path %>

<%if restaurant_signed_in? %>
  <%if current_restaurant.id == @dish.restaurant_id%>
    <div>
      <%= link_to "Edit this dish", edit_dish_path(@dish) %> 
      <%= button_to "Destroy this dish", @dish, method: :delete %>
    </div>
  <%end%>
<%end%>


<%if reviewer_signed_in? %>
  <div id="dishes">
    LISTA RECENSIONI:
    <% (Review.all).each do |review| %>
      <%if @dish.id == review.dish_id %>
        <%= render review %>
        <p> <%#= link_to "Show this dish", @dish %> </p> 
      <%end%>
    <% end %>
  </div>
  <%#SI PUO' METTERE SOLO UNA RECENSIONE PER PIATTO DEL RISTORANTE?, da controllare%>
  <%#l'if è sbagliato%>
    <% (Review.all).each do |review| %>
      <%if @dish.id == review.dish_id  && review.reviewer_id == current_reviewer.id%>
        <%#= link_to "LA TUA RECENSIONE", review %><br>
        LA TUA RECENSIONE: <%=render review%>
        <%#= link_to "LA TUA RECENSIONE", review %><br>
      <%elsif !(@dish.id == review.dish_id  && review.reviewer_id == current_reviewer.id)%>
        <%= link_to "CREA NUOVA RECENSIONE", new_review_path %><br>
      <%end%>
    <% end %>
    
<%end%>