config/routes.rb
Rails.application.routes.draw do
 
  devise_for :reviewers#, controllers: { omniauth_callbacks: 'reviewer/omniauth_callbacks' }
  devise_for :restaurants

  devise_for :omni_users, controllers: { omniauth_callbacks: 'omni_users/omniauth_callbacks' }

  get 'search/index'
  get 'search/show'
  get 'search/edit'
  get 'search/update'
  get 'search/search_restaurant'
  get 'search/search_dish'
  get 'search/index'
  get 'search/show'
  get 'search/edit'
  get 'search/update'
  get 'home/index'
# This is for being able of testing the application with cucumber. Since we are not using devise defaults login
  match 'login/:id' => 'restaurant#login', :as => 'login', :via => [:get] if Rails.env.test?

  
  resources :reports, :except => :index
  resources :dishes, :except => :index
  resources :restaurants, :except => :index
  resources :reviews, :except => :index
  resources :reviewers, :except => :index
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "home#index"

  get '/search_restaurant', to: 'search#search_restaurant'
  get '/search_dish', to: 'search#search_dish'

  #default, per percorsi inesistenti (es.No route matches [GET])
  #se danno problemi commentare
  #get '*all', to: 'home#index', constraints: lambda { |req|
   # req.path.exclude? 'rails/active_storage'
  #}
  
  #le recensioni possono essere viste ed accedute solo attraverso i ristoranti e recensori, ma non tutte le funzionalita'
  #resources :restaurant do
	#	resources :reviews, only: [:new, :show, :create]
  #  resources :dish, only: [:new, :show, :create, :delete]
	#end
  #idem
  #resources :reviewer do
	#	resources :reviews, only: [:show, :edit, :index]
	#end

  #resources :restaurant, only: [:index, :new, :show, :create]


end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    validates :name, :username, presence: true
    validates :username,  uniqueness: true
    validates :password, presence: true, on: :create
    validates :password_confirmation, presence: true, on: :create

    has_one_attached :profile_picture, service: :google
    validates :profile_picture,  blob: { content_type: :image }
    #has_one :omniuser
    after_initialize :init_values

    def self.from_google(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |restaurant|
        #campi da assegnare al modello restaurant, tramite oauth
        restaurant.uid = auth.uid
        restaurant.provider = auth.provider
        restaurant.email = auth.info.email
        restaurant.password = Devise.friendly_token[0, 20]
        #creo un username, tecnicamente univoco, in maniera incrementale per disponibilità
        i = -1
        s_username = auth.info.first_name.to_s << "-" << auth.info.last_name.to_s
        t_username = s_username
        while (Restaurant.exists?(username: t_username))
          i += 1
          t_username = s_username + i.to_s
        end
        restaurant.name = t_username
        restaurant.username = t_username
        restaurant.profile_picture.attach(io: URI.parse(auth.info.image).open, filename: "profile_picture.jpg")
        restaurant.description = "Sono il ristorante " << auth.info.name << " e sono registrato tramite account Google! "
      end
    end

    def init_values
      self.ta_rating ||= 0.0
    end
    
end

app/controllers/restaurant/confirmations_controller.rb
# frozen_string_literal: true

class Restaurant::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/restaurant/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Restaurant::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  #OBSOLETO, SI USA OMNI_USER
  
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
  
  def auth
    #risposta auth google, contiene dei campi utili
    #https://github.com/zquestz/omniauth-google-oauth2
    @auth ||= request.env['omniauth.auth']
  end
end

app/controllers/restaurant/passwords_controller.rb
# frozen_string_literal: true

class Restaurant::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/restaurant/registrations_controller.rb
# frozen_string_literal: true

class Restaurant::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/restaurant/sessions_controller.rb
# frozen_string_literal: true

class Restaurant::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/restaurant/unlocks_controller.rb
# frozen_string_literal: true

class Restaurant::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[ show edit update destroy ]

  # GET /restaurants or /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1 or /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    session['userType']='Restaurant'
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # This action is supposed to only be accessed in the test environment.
  # This is for being able of running the cucumber tests.
  def login
    @restaurant = Restaurant.find(params[:id])
    sign_in(@restaurant)
    current_restaurant = @restaurant
    render :text => "restaurant logged in"
  end

  # POST /restaurants or /restaurants.json
  def create
    session['userType']='Restaurant'
    @restaurant = Restaurant.new(restaurant_params)
    respond_to do |format|
      if @restaurant.save
        TasteAdvisorMailer.with(user: @restaurant, type: "Restaurant").welcome_email.deliver!
        format.html { redirect_to restaurant_url(@restaurant), notice: "Restaurant was successfully created." }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1 or /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to restaurant_url(@restaurant), notice: "Il ristorante è stato aggiornato correttamente" }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1 or /restaurants/1.json
  def destroy
    @restaurant.destroy

    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: "Il ristorante è stato eliminato correttamente" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :username, :website, :description, :telephone_number, :address, :profile_picture, :password, :password_confirmation)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modifica</title>

    <%= stylesheet_link_tag "modRistorante.css" %>
</head>
<body>

    <%= form_with(model: restaurant) do |form| %>
        <% if restaurant.errors.any? %>
        <div style="color: red">
            <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>
        <ul>
        <% restaurant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
        </ul>
        </div>
    <% end %>

    <div id = "middle">
        <div id = "row_m1">
            <div id = "editable">
                <div id = "foto">
                    <div id = "image">
                        <% if current_restaurant.profile_picture.attached? %>
                            <img src="<%= url_for(current_restaurant.profile_picture)%>" alt="PP" width="250" height="250" id="profile_pic">
                        <% end %>
                    </div>
                </div>
                <div id = "photo_picker">
                        <!--
                        <label id = "lbl_file_loader">Seleziona una foto</label>
                        </br>
                        <input type="file" class = "form-control-file">
                        -->
                        <div id = "input_img"><%= form.file_field :profile_picture, direct_upload: false, accept:"image/*" %> </div>
                </div>
            </div>
            <div id = "user_desc_1">
                <div id = "username"><%= current_restaurant.username%></div>
                <div><%= form.text_area :description, :class => "form-control", :placeholder => "Inserisci descrizione", :rows =>"3" %></div>
            </div>
            <div id = "user_desc_2">
                <div class = "form_labels">
                    <div id = "position">Indirizzo</div>
                    <div id = "website">Sito</div>
                    <div id = "phone_number">Telefono</div>
                </div>
                <div class = "form_fields">
                    <%= form.text_field :address %>
                    <%= form.text_field :website %>
                    <%= form.text_field :telephone_number %>
                </div>
            </div>
        </div>
        <div id = "row_m2">
                <div id = "save_div"><%= form.submit "Salva", :class => "btn btn-success",:id => "save_btn"%></div>
                <div id = "cancel_div"><%= link_to "Annulla", current_restaurant, :class => "btn btn-danger", :id => "cancel_btn" %></div>
        </div>
    </div>
</body>
</html>
<%end%>

app/views/restaurants/_restaurant.html.erb
<div id="<%= dom_id restaurant %>">

  UTENTE RISTORANTE<br>
  ID:<%= restaurant.id %><br>
  USERNAME:<%= restaurant.username %><br>
  NAME:<%= restaurant.name %><br>
  TEL:<%= restaurant.telephone_number%><br>
  ADDRESS:<%= restaurant.address%><br>
  EMAIL:<%= restaurant.email %><br>
  <br>
  <% if restaurant.profile_picture.attached? %>
      <img src="<%= url_for(restaurant.profile_picture)%>" alt="PP" width="100" height="100">
  <% end %>

  <br><br>

  <%#https://github.com/zilverline/google-maps%>

  <%if restaurant.address.to_s != "" and Google::Maps.geocode(restaurant.address).to_s != "[]"%>
      <% place = Google::Maps.place(Google::Maps.places(restaurant.address).first.place_id)%>
      <%#= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=15&size=400x300&center=#{place.latitude},#{place.longitude}&key=AIzaSyCXBINbcHzq6sqrq3ku3ABFKFahO7ZpgiI", alt: "Map" %>
      <%#=https://developers.google.com/maps/documentation/embed/embedding-map%>
      <iframe
        width="400"
        height="300"
        style="border:0"
        loading="eager"
        allowfullscreen
        referrerpolicy="no-referrer-when-downgrade"
        src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCXBINbcHzq6sqrq3ku3ABFKFahO7ZpgiI
        &q= <%=place%>
        &zoom=15
        &language=it">
      </iframe>
  <%end%>
  
</div>

app/views/restaurants/edit.html.erb
<%= render "form", restaurant: @restaurant %>

<!--
<div>
  <%= link_to "Show this restaurant", @restaurant %>
  <%= link_to "Back to restaurant", current_restaurant %>
</div>
-->

app/views/restaurants/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Restaurants</h1>

<div id="restaurants">
  <% @restaurants.each do |restaurant| %>
    <%= render restaurant %>
    <p>
      <%= link_to "Show this restaurant", restaurant %>
    </p>
  <% end %>
</div>

<%= link_to "New restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render "form", restaurant: @restaurant %>
<% session['userType'] %>
<br>

<div>
  <%= link_to "Back to restaurants", restaurants_path %>
</div>

app/views/restaurants/show.html.erb
<!-- tolto = da render in modo da poter pescare informazioni senza stamparle tutte,
       segue esempio username-->
  
<!--
<% render @restaurant %> 

  ADDRESS:<%= @restaurant.address %><br>
  <p>
  <% Dish.all.each do |dish| %>
    <%if dish.restaurant_id == @restaurant.id %>
       <%= render dish%>
       <p> <%= link_to "Show this dish", dish %> </p> 
    <%end%>

  <% end %>

  </p>

<div>
  <%= link_to "Edit restaurant", edit_restaurant_path(@restaurant) %>
</div>
-->

<!--
<div>
  <%= link_to "Back to restaurants", restaurants_path %>
</div>
-->


<%# render @restaurant %> 

<%@rating_gmaps = nil%>

<%if @restaurant.address != nil and @restaurant.address.length > 0 %>
  <%
    #https://stackoverflow.com/questions/21542530/rails-get-values-of-http-response
    #https://ruby-doc.org/stdlib-3.1.2/libdoc/net/http/rdoc/Net/HTTP.html
    #https://developers.google.com/maps/documentation/places/web-service/search-nearby#json
    require "uri"
    require "net/http"
    require 'json'
    string_query = "https://maps.googleapis.com/maps/api/place/details/json?place_id="
    string_query += Google::Maps.places(@restaurant.name + "," + @restaurant.address).first.place_id.to_s
    string_query += "&language=it&key=AIzaSyCXBINbcHzq6sqrq3ku3ABFKFahO7ZpgiI"
    
    #string_query2 = "https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-33.8670522%2C151.1957362&radius=1500&type=restaurant&keyword=cruise&key=AIzaSyCXBINbcHzq6sqrq3ku3ABFKFahO7ZpgiI"
    url = URI(string_query)

    https = Net::HTTP.new(url.host, url.port)
    https.use_ssl = true

    request = Net::HTTP::Get.new(url)
    @response = JSON.parse(https.request(request).body)
    @rating_gmaps = ""
  %>
        
      <%if @response != nil and @response["result"] != nil and @response["result"]["rating"] != nil
          @rating_gmaps = @response["result"]["rating"].to_s
        end
      %>
<%end%>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profilo</title>

    <%= stylesheet_link_tag "general_tags.css" %>
    <%= stylesheet_link_tag "ristorante.css" %>

</head>
<body>
    <div id = "middle">
      <%if restaurant_signed_in? && current_restaurant.id == @restaurant.id%>
        <div id = "foto">
          <% if @restaurant.profile_picture.attached? %>
            <div><img src="<%= url_for(@restaurant.profile_picture)%>" alt="PP" width="100" height="100"></div>
          <%else%>
            <%= image_tag("missing_user.png", :width => "100", :height => "100")%>
          <% end %>
          <div id = "pic_lbl">Foto profilo</div>
        </div>
        <div id = "infos">
          <div id = "user_desc_1">
            <div id = "username"><%= @restaurant.username %></div>
            <div id = "rating_ta"> Rating TasteAdvisor : <%= @restaurant.ta_rating.truncate(2)%></div>
            <%if @rating_gmaps != nil%>
              <div id = "rating_gm"> Rating GMaps : <%= @rating_gmaps%></div>
            <%end%>
            <div id = "description">
              <% if(@restaurant.description == nil || @restaurant.description.length == 0) %>
                Questo ristorante non ha una descrizione
                <!-- restituisce questa stringa al posto della descrizione nel caso in cui sia vuota -->
              <% else %>
                <%= @restaurant.description%>
              <% end %>
            </div>
          </div>
          <div id = "user_desc_2">
            <div id = "position"><%= @restaurant.address %></div>
            <%if @restaurant.website != nil%>
              <%if URI.parse(@restaurant.website).host.to_s != "" %>
                <div id = "website"><%= link_to  URI.parse(@restaurant.website).host, "http://#{URI.parse(@restaurant.website).host}", target: :_blank , rel: 'noopener noreferrer'%></div>
              <%else%>
                <div id = "website"><%= link_to  @restaurant.website, "http://#{@restaurant.website}", target: :_blank, rel: 'noopener noreferrer' %></div>
              <%end%>
            <%end%>
            <div id = "phone_number"><a href = "tel:<%= @restaurant.telephone_number %>"><%= @restaurant.telephone_number %></a></div>
            <div id = "mail_to"><a href="mailto:<%= @restaurant.email%>">Invia una mail</a></div>
          </div>
        </div>
        <div id = "modify">
          <%= button_to "Modifica profilo", edit_restaurant_path(@restaurant), method: :get, :class => "btn btn-success btn-responsive"%>
        </div>
      <%else%>
      <div id = "col_m1">
        <div id = "foto">
          <% if @restaurant.profile_picture.attached? %>
            <div><img src="<%= url_for(@restaurant.profile_picture)%>" alt="PP" width="100" height="100"></div>
          <%else%>
            <%= image_tag("missing_user.png", :width => "100", :height => "100")%>
          <% end %>
          <div id = "pic_lbl">Foto profilo</div>
        </div>
      </div>
      <div id = "col_m2">
        <div id = "username"><%= @restaurant.username %></div>
        <div id = "rating_ta"> Rating TasteAdvisor : <%= @restaurant.ta_rating.truncate(2)%></div>
        <%#il rating gmaps ha senso se il ristorante esiste su gmaps%>
        <%if @rating_gmaps != nil%>
          <div id = "rating_gm"> Rating GMaps : <%= @rating_gmaps%></div>
        <%end%>
        <div id = "description_mod">
          <% if(@restaurant.description == nil) %>
            Questo ristorante non ha una descrizione
            <!-- restituisce questa stringa al posto della descrizione nel caso in cui sia vuoto -->
          <% else %>
            <%= @restaurant.description%>
          <% end %>
          </div>
      </div>
      <% end %>
    </div>
    <div id = "dishes_and_other_infos">
      <div id = "col_d1">
      <% if restaurant_signed_in? %>
        <div id = "dishes_div_restaurant">
          <div id = "header_and_insertions">
            <div id = "header">I miei piatti: </div>
            <% if restaurant_signed_in? && current_restaurant.id == @restaurant.id %>
              <%= link_to "Nuovo piatto", new_dish_path, :id => "insert_dishes", :class => "btn btn-success btn-responsive" %>
            <% end %>
          </div>
      <% else %>
        <div id = "dishes_div">
          <div id = "header">I piatti: </div>
      <%end%>
        <div id = "inserted_dishes">
          <% (Dish.all).each do |dish|%>
            <% if dish.restaurant_id == @restaurant.id %>
              <div class = "piattino">
              <%= link_to dish_path(dish) do %>
                <div class = "interno_piattino">
                 <div id = "foto_piatto">
                    <% if (dish.images[0] != nil)%>
                      <img src="<%= url_for(dish.images[0])%>" alt="foto_piatto" class="dish_pic">
                    <% else %>
                      <%= image_tag("missing_dish.png", :class => "dish_pic")%>
                    <% end %>
                  </div>
                  <div class = "info_piatto">
                    <div class = "nome_piattino"><b><%= dish.name%></b></div>
                    <div class = "prezzo_piattino">Prezzo: <%= dish.price%></div>
                    <div class = "rating_piattino">Rating: <%= dish.avg_rating.round(2)%></div>
                  </div>
                  <div id = "mod_btns">
                    <% if reviewer_signed_in? %>
                      <%check_exist = 0.0%>
                      <% (Review.all).each do |review| %>
                          <%if review.dish_id == dish.id and review.reviewer_id == current_reviewer.id %>
                              <%check_exist = 1.0%>
                          <%end%>
                      <%end%>
                      <%if check_exist == 0.0%>
                          <div class = "div_review"><%= link_to "Lascia recensione", new_review_path(dish_id: dish.id), :class => "btn btn-warning", :id =>"review_btn" %></div>
                      <%end%>
                      
                    <% elsif restaurant_signed_in? && current_restaurant.id == @restaurant.id %>
                      <%= link_to "Modifica", edit_dish_path(dish), :class => "btn btn-success btn-responsive-dish" %>
                      <%= button_to "Rimuovi", dish, method: :delete, :class => "btn btn-danger btn-responsive-dish" %>
                    <% end %>
                  </div>
                </div>
              </div>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
        <div id = "col_d2">
          <div id = "map_addresses">
            <div id = "map">
              <%if @restaurant.address.to_s != "" and Google::Maps.geocode(@restaurant.address).to_s != "[]"%>
                  <% place = Google::Maps.place(Google::Maps.places(@restaurant.address).first.place_id)%>
                  <iframe
                    width="600"
                    height="210"
                    style="border:0"
                    loading="eager"
                    referrerpolicy="no-referrer-when-downgrade"
                    src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCXBINbcHzq6sqrq3ku3ABFKFahO7ZpgiI
                    &q= <%=place%>
                    &zoom=15
                    &language=it">
                  </iframe>
                <% else %>
                  <%place = Google::Maps.place(Google::Maps.places("Italy").first.place_id)%>
                  <iframe
                    width="600"
                    height="245"
                    style="border:0"
                    loading="lazy"
                    referrerpolicy="no-referrer-when-downgrade"
                    src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCXBINbcHzq6sqrq3ku3ABFKFahO7ZpgiI
                    &q= <%=place%>
                    &zoom=15
                    &language=it">
                  </iframe>
                
              <%end%>
            </div>
            <div id = "address_info">
            <div id = "position"><%= @restaurant.address %></div>
            <%if @restaurant.website != nil%>
              <%if URI.parse(@restaurant.website).host.to_s != "" %>
                <div id = "website"><%= link_to  URI.parse(@restaurant.website).host, "http://#{URI.parse(@restaurant.website).host}", target: :_blank , rel: 'noopener noreferrer'%></div>
              <%else%>
                <div id = "website"><%= link_to  @restaurant.website, "http://#{@restaurant.website}", target: :_blank, rel: 'noopener noreferrer' %></div>
              <%end%>
            <%end%>
            <div id = "phone_number"><a href = "tel:<%= @restaurant.telephone_number %>"><%= @restaurant.telephone_number %></a></div>
            <div id = "mail_to"><a href="mailto:<%= @restaurant.email%>">Invia una mail</a></div>
            </div>
          </div>
        </div>
      </div>
  </div>
  </body>
</html>