config/routes.rb
Rails.application.routes.draw do
 
  devise_for :reviewers#, controllers: { omniauth_callbacks: 'reviewer/omniauth_callbacks' }
  devise_for :restaurants

  devise_for :omni_users, controllers: { omniauth_callbacks: 'omni_users/omniauth_callbacks' }

  get 'search/index'
  get 'search/show'
  get 'search/edit'
  get 'search/update'
  get 'search/search_restaurant'
  get 'search/search_dish'
  get 'search/index'
  get 'search/show'
  get 'search/edit'
  get 'search/update'
  get 'home/index'
# This is for being able of testing the application with cucumber. Since we are not using devise defaults login
  match 'login/:id' => 'restaurant#login', :as => 'login', :via => [:get] if Rails.env.test?

  
  resources :reports, :except => :index
  resources :dishes, :except => :index
  resources :restaurants, :except => :index
  resources :reviews, :except => :index
  resources :reviewers, :except => :index
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "home#index"

  get '/search_restaurant', to: 'search#search_restaurant'
  get '/search_dish', to: 'search#search_dish'

  #default, per percorsi inesistenti (es.No route matches [GET])
  #se danno problemi commentare
  #get '*all', to: 'home#index', constraints: lambda { |req|
   # req.path.exclude? 'rails/active_storage'
  #}
  
  #le recensioni possono essere viste ed accedute solo attraverso i ristoranti e recensori, ma non tutte le funzionalita'
  #resources :restaurant do
	#	resources :reviews, only: [:new, :show, :create]
  #  resources :dish, only: [:new, :show, :create, :delete]
	#end
  #idem
  #resources :reviewer do
	#	resources :reviews, only: [:show, :edit, :index]
	#end

  #resources :restaurant, only: [:index, :new, :show, :create]


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[ show edit update destroy ]

  #metodi std rails scaffold

  # GET /reviews or /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1 or /reviews/1.json
  def show
    
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
    
    #edit(controller)->form (view _form.html.erb di review)->update(controller)
    #@review = Review.find(params[:id])
  
  end

  # POST /reviews or /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to review_url(@review), notice: "La recensione è stata creata correttamente" }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    #presi da _form.html.erb di review

    #@review.rating1 = params[:rating1] 
    #@review.rating2 = params[:rating2]
    #@review.rating3 = params[:rating3]
    #@review.description = params[:description]
    #@review.imgs = params[:imgs]

    #@review.dish_id = params[:dish_id]
    #@review.reviewer_id = params[:reviewer_id]
    #equivalenti a @review.update(review_params)
    
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to review_url(@review), notice: "La recensione è stata aggiornata correttamente" }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    @review.destroy

    respond_to do |format|
      format.html { redirect_to home_index_path, notice: "La recensione è stata cancellata correttamente" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:rating1, :rating2, :rating3, :description, :reviewer_id, :dish_id, images: [])
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_with(model: review) do |form| %>

  <% if review.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div id = "middle">
        <div id = "midtop">
            <div id = "col1">
                <div id = "foto">
                    <div id = "image">
                       <%= form.file_field :images, multiple: true, direct_upload: false, accept:"image/*" %>
                    </div>
                    <% if @review.id != nil%>
                        <div id = "image_lbl">Reinserisci le foto e aggiungine altre</div>
                    <%else%>
                        <div id = "image_lbl">Inserisci le foto</div>
                    <%end%>
                </div>
            </div>
            <div id = "col2">
                <div id = "ratings">
                    <div class = "rating" id = "gusto">
                        <div id = "gusto_lbl">Gusto</div>
                        <div class = "rtg" id = "gusto_rtg">
                            <div id = "gusto_select">
                            <%= form.select :rating1, ["1", "2", "3", "4", "5"], :name => "numbers", autofocus: true, :onchange => "return modificaValore1(this);" %>
                            </div>
                            <div class = "pb" id = "gusto_pb">
                                <div class="progress">
                                <!--TODO: Cambiare il rating fisso della pg in rating1 variabile-->
                                    <div class="progress-bar progress-bar-striped bg-info" role="progressbar" style="width: 20%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" id = "pg1"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class = "rating" id = "impiattamento">
                        <div id = "impiattamento_lbl">Impiattamento</div>
                        <div class = "rtg" id = "impiattamento_rtg">
                            <div id = "impiattamento_select">
                            <%= form.select :rating2, ["1", "2", "3", "4", "5"], :name => "numbers", autofocus: true, :onchange => "return modificaValore2(this);" %>                                
                            </div>
                            <div class = "pb" id = "impiattamento_pb">
                                <div class="progress">
                                    <!--TODO: Cambiare il rating fisso della pg in rating2 variabile-->
                                    <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: 20%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" id = "pg2"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class = "rating" id = "originalità">
                        <div id = "originalità_lbl">Originalità</div>
                        <div  class = "rtg" id = "originalità_rtg">
                            <div id = "originalità_select">
                                <%= form.select :rating3, ["1", "2", "3", "4", "5"], :name => "numbers", autofocus: true, :onchange => "return modificaValore3(this);" %>
                            </div>
                            <div class = "pb" id = "impiattamento_pb">
                                <div class="progress">
                                    <div class="progress-bar progress-bar-striped bg-warning" role="progressbar" style="width: 20%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" id = "pg3"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div id = "description">
                    <%= form.label :description, "Descrizione ", style: "display: block", :id => "descr_id" %>
                    <%= form.text_area :description, :class => "form-control", :placeholder => "Inserisci descrizione", :rows =>"3" %>
                </div>
                
            </div>
        </div>
        <div id = "midbottom">
            <%= form.hidden_field :dish_id, value: params[:dish_id] %>
            <%= form.hidden_field :reviewer_id, value: current_reviewer.id %>

            <div id = "confirm">
                    <%= form.submit "Conferma", :class => "btn btn-success", :id => "confirm_btn"%>
            </div>
            <div id = "cancel">
            <% if @review.id != nil%>
                <%= link_to "Annulla modifiche", review_path(@review), :class => "btn btn-danger", :id => "cancel_btn" %>
            <%else%>
                <%= link_to "Annulla creazione", dish_path(params[:dish_id]), :class => "btn btn-danger", :id => "cancel_btn"  %>
            <%end%>
            </div>
        </div>
    </div>

<% end %>

<%= stylesheet_link_tag "nuovaRecensione.css" %>

<script>
        document.getElementById("review_rating1").setAttribute("onchange", "return modificaValore1(this);");
        document.getElementById("review_rating2").setAttribute("onchange", "return modificaValore2(this);");
        document.getElementById("review_rating3").setAttribute("onchange", "return modificaValore3(this);");

        function modificaValore1(select){
            var selezionato = select.options[select.selectedIndex].value;
            document.getElementById("pg1").setAttribute("style", "width: "+  String(Number(selezionato)*20)+"%");
        }
        function modificaValore2(select){
            var selezionato = select.options[select.selectedIndex].value;
            document.getElementById("pg2").setAttribute("style", "width: "+  String(Number(selezionato)*20)+"%");
        }
        function modificaValore3(select){
            var selezionato = select.options[select.selectedIndex].value;
            document.getElementById("pg3").setAttribute("style", "width: "+  String(Number(selezionato)*20)+"%");
        }
</script>

app/views/reviews/_review.html.erb
<%= stylesheet_link_tag "recensione.css" %>
<div id="<%= dom_id review %>">
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0";
    fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));

    window.fbAsyncInit = function(){  
console.log("FB Object initiated");
FB.XFBML.parse(); // 
    };
</script>
<div id = "middle">
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/it_IT/sdk.js#xfbml=1&version=v15.0&appId=891463521856520&autoLogAppEvents=1" nonce="9dbJ8tPj"></script>
    <div id = "col1">
        <%if (review.reviewer_id != nil) && (review.dish_id != nil)%>
            <div id = "names_div">
                <div id = "plate_name">Nome del piatto: <%=Dish.find(review.dish_id).name%>
                    <br><%= link_to "Vai al piatto", dish_path(review.dish_id), :class => "link" %>
                </div>
                
                <div id = "restaurant_name">Presso il ristorante: <%=Restaurant.find(Dish.find(review.dish_id).restaurant_id).name%>
                    <br><%= link_to "Vai al ristorante", restaurant_path(Restaurant.find(Dish.find(review.dish_id).restaurant_id).id), :class => "link" %>
                </div>
                </div>   
        <%end%>
        <div id = "ratings">
            <div class = "rating" id = "gusto">
                <div id = "gusto_lbl">Gusto</div>
                <div class = "rtg" id = "gusto_rtg">
                    <div class = "values" id = "gusto_value">
                        <%= review.rating1%>/5
                    </div>
                    <div class = "pb" id = "gusto_pb">
                        <div class="progress">
                            <div class="progress-bar progress-bar-striped bg-info" role="progressbar" style="width: <%= review.rating1*20%>%" aria-valuenow="<%= review.rating1*20 %>" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class = "rating" id = "impiattamento">
                <div id = "impiattamento_lbl">Impiattamento</div>
                <div class = "rtg" id = "impiattamento_rtg">
                    <div class = "values" id = "impiattamento_value">
                    <%= review.rating2%>/5
                    </div>
                    <div class = "pb" id = "impiattamento_pb">
                        <div class="progress">
                            <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: <%= review.rating2*20%>%" aria-valuenow="<%= review.rating2*20 %>" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class = "rating" id = "originalità">
                <div id = "originalità_lbl">Originalità</div>
                <div  class = "rtg" id = "originalità_rtg">
                    <div class = "values" id = "originalità_value">
                    <%= review.rating3%>/5
                    </div>
                    <div class = "pb" id = "impiattamento_pb">
                        <div class="progress">
                            <div class="progress-bar progress-bar-striped bg-warning" role="progressbar" style="width: <%= review.rating3*20%>%" aria-valuenow="<%= review.rating3*20 %>" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <textarea id = "description" rows="4" cols="50" disabled="true"> <%= review.description%> </textarea>
        <%if (review.reviewer_id != nil) && (review.dish_id != nil)%>
            <% username = Reviewer.find(review.reviewer_id).username %>
            <div id = "user_name">Recensione effettuata da <%= link_to username, reviewer_path(review.reviewer_id) %> </div>
        <%end%>
    </div>
    <div id = "col2">
        <% i = -1 %>
        <div id = "foto_recensione">      
            <div id = "foto_label">Foto della recensione: </div>    
            <%if review.images[0] != nil%>
                <% i = 0 %>
                <% r = 0 %>
                    <% while review.images[i] != nil%>
                        <div class = "imgs_row" id = "imgs_row_<%=r%>">
                        <% j = 0 %>
                        <% while review.images[i] != nil && j <  3 %>
                            <img src="<%= url_for(review.images[i])%>" alt="foto_recensione" class = "review_img">
                            <%j = j + 1%>
                            <%i = i + 1%>
                        <% end %>
                        <% r = r + 1%>
                        </div>
                    <% end %>
                            <!--
                            <div id = "foto_recensione" class="carousel carousel-fade" data-bs-ride="carousel"> 
                            <div class="carousel-inner">  

                            <%# if (i == 0)%>
                                <div class = "carosuel-item active">
                            <%# else %>
                                <div class = "carousel-item">
                            <%# end %>
                            <img src="<%#= url_for(review.images[i])%>" alt="foto_recensione" class = "review_img">
                            <%#i += 1%>
                            </div>
                        <%#end%>
                        -->
              </div>
            <%end%>
            <% if (i == -1) %>
               <div id = "no_foto_label"> nessuna foto caricata </div>
            <% end %>
        <div class="fb-share-button" data-href="https://tasteadvisor.herokuapp.com/reviews/<%= review.id%>"
            data-layout="button_count" data-size="large">
            <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Condividi</a>
        </div>
        </div>
    </div>
    

</div>

            

app/views/reviews/edit.html.erb
<%= render "form", review: @review %>

app/views/reviews/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Reviews</h1>

<div id="reviews">
  <% @reviews.each do |review| %>
    <%= render review %>
    <p>
      <%= link_to "Show this review", review %>
    </p>
  <% end %>
</div>

<%#= link_to "New review", new_review_path %>

app/views/reviews/new.html.erb
<%= render "form", review: @review %>

app/views/reviews/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @review %>

<%if reviewer_signed_in?%>
  <% if current_reviewer.id == @review.reviewer_id %>
    <div id = "review_btns">
      <div id = "edit_btn">
        <%= link_to "Modifica recensione", edit_review_path(@review, dish_id: @review.dish_id), :class => "btn btn-primary", :id => "mod_link" %>
      </div>
      <div id =  "destroy_btn">
        <%= button_to "Elimina recensione", @review, method: :delete, :class => "btn btn-danger", :id => "dest_link" %>
      </div>
    </div>
  <%else%>
    <div id = "review_btns">
      <div id = "report_div">

        <%check_exist = 0.0%>
        <% (Report.all).each do |report| %>
            <%if report.reporterId == current_reviewer.id  and report.targetType == "review" and report.targetId == @review.id %>
                <%check_exist = 1.0%>
            <%end%>
        <%end%>

        <%if check_exist == 0.0%>
          <%=form_with url: new_report_path, method: :get do |form| %>
              <%= form.hidden_field :report_id, value: @review.id%>
              <%= form.hidden_field :report_type, value:"review"%>
              <%= form.hidden_field :reporter_id, value: current_reviewer.id %>
              <%= submit_tag "Segnala Recensione", :class => "btn btn-danger", :id => "report_link"%>
          <%end%>
        <%end%>

      </div>
    </div>
  <%end%>
<%elsif restaurant_signed_in?%>
  <div id = "review_btns">
      <div id = "report_div">
  
        <%check_exist = 0.0%>
        <% (Report.all).each do |report| %>
            <%if report.reporterId == current_restaurant.id  and report.targetType == "review" and report.targetId == @review.id %>
                <%check_exist = 1.0%>
            <%end%>
        <%end%>

        <%if check_exist == 0.0%>
          <%=form_with url: new_report_path, method: :get do |form| %>
              <%= form.hidden_field :report_id, value: @review.id%>
              <%= form.hidden_field :report_type, value:"review"%>
              <%= form.hidden_field :reporter_id, value: current_restaurant.id %>
              <%= submit_tag "Segnala Recensione", :class => "btn btn-danger", :id => "report_link"%>
          <%end%>
        <%end%>
        
        </div>
  </div>
<%else%>
  <div id = "review_btns">
      <div id = "report_div">
        <%= button_to "Segnala recensione", new_reviewer_session_path, :class => "btn btn-danger", :id => "report_link" %>
      </div>
  </div>
<%end%>